"""Agent 常量 — 魔术数字集中管理"""
# 输出限制
MAX_TOOL_RESULT_LENGTH = 20000
MAX_REVIEW_CODE_LENGTH = 8000  
MAX_OUTPUT_LENGTH = 5000
ERROR_MESSAGE_MAX_LENGTH = 500

# API 默认值
DEFAULT_MAX_TOKENS = 8192
DEFAULT_HTTP_TIMEOUT = 120.0

# 性能参数
STREAM_YIELD_DELAY = 0.01
CODE_EXEC_TIMEOUT = 30

# 缓存
PROMPT_CACHE_TTL_SECONDS = 300
TOOL_CACHE_TTL_SECONDS = 30
TOOL_CACHE_MAX_SIZE = 50
